### ISSUE TITLE
[QUESTION] Use this plugin with win64-shipping.exe in IDA?

### ISSUE THREAD

**Issue by wrongrior** [Fischsalat/IDAExecFunctionsImporter#1]
I have .idmap and installed this plugin on IDA, but I don't know how to use? just open win-shipping.exe in IDA and use this plugin?

**Comment by Fischsalat** [comment]
yes, with the .idmap file generated by the dumper.

**Comment by FlashCoder2024** [comment]
Do you know how I can install the plugin for IDA?

> yes, with the .idmap file generated by the dumper.
