### ISSUE TITLE
Working IDA pro 9 for you

### ISSUE THREAD

**Issue by AlestackOverglow** [Fischsalat/IDAExecFunctionsImporter#4]
Your ida 9 fork is not work, so take working code or just check my fork

```
#include <Windows.h>
#include <ida.hpp>
#include <idp.hpp>
#include <loader.hpp>
#include <bytes.hpp>
#include <funcs.hpp>
#include <fpro.h>
#include <name.hpp>
#include <diskio.hpp>
#include <kernwin.hpp>

#include "ida_file.h"
#include "ida_string.h"

size_t get_real_imagebase()
{
	return getinf(INF_IMAGEBASE);
}

class plugin_ctx_t : public plugmod_t
{
public:
	// Constructor
	plugin_ctx_t()
	{
		msg("MyPlugmod: Constructor called.\n");
	}

	// Destructor
	virtual ~plugin_ctx_t()
	{
		msg("MyPlugmod: Destructor called.\n");
	}
	virtual bool idaapi run(size_t) override
	{
		ida_string result = ask_file(false, "*.idmap", "Load the file, or %s", "die!");
		
		ida_file selected_file(result, ida_file::open_mode::binary_read_only);

		auto image_base = get_real_imagebase();
		msg("Imagebase: 0x%llX\n", image_base);

		hook_type_t processor_hook = HT_IDP;

		if (selected_file.is_open())
		{
			while (selected_file.can_read_more())
			{
				uint32 offset = selected_file.read<uint32>();
				uint16 name_len = selected_file.read<uint16>();

				ida_string name_string = selected_file.read_string(name_len);

				set_name(image_base + offset, name_string.c_str());

				//msg("offset: 0x%X\n", offset);
				//msg("name_len: 0x%X\n", name_len);
				//msg("name_string: %s\n", name_string.c_str());
			}
		}

		return true;
	}
};


//--------------------------------------------------------------------------
static plugmod_t* idaapi init(void)
{
	return new plugin_ctx_t;
}

//--------------------------------------------------------------------------
plugin_t PLUGIN =
{
  IDP_INTERFACE_VERSION,
  PLUGIN_UNL            // Unload the plugin immediately after calling 'run'
  | PLUGIN_MULTI,       // The plugin can work with multiple idbs in parallel
  init,                 // initialize
  nullptr,
  nullptr,
  nullptr,              // long comment about the plugin
  nullptr,              // multiline help about the plugin
  "IDAExecFunctionsImporter", // the preferred short name of the plugin
  "Ctrl-Alt-A",         // the preferred hotkey to run the plugin
};
```

**Comment by FlashCoder2024** [comment]
> Your ida 9 fork is not work, so take working code:
> 
> ```
> `#include <Windows.h>
> #include <ida.hpp>
> #include <idp.hpp>
> #include <loader.hpp>
> #include <bytes.hpp>
> #include <funcs.hpp>
> #include <fpro.h>
> #include <name.hpp>
> #include <diskio.hpp>
> #include <kernwin.hpp>
> 
> #include "ida_file.h"
> #include "ida_string.h"
> 
> size_t get_real_imagebase()
> {
> 	return getinf(INF_IMAGEBASE);
> }
> 
> class plugin_ctx_t : public plugmod_t
> {
> public:
> 	// Constructor
> 	plugin_ctx_t()
> 	{
> 		msg("MyPlugmod: Constructor called.\n");
> 	}
> 
> 	// Destructor
> 	virtual ~plugin_ctx_t()
> 	{
> 		msg("MyPlugmod: Destructor called.\n");
> 	}
> 	virtual bool idaapi run(size_t) override
> 	{
> 		ida_string result = ask_file(false, "*.idmap", "Load the file, or %s", "die!");
> 		
> 		ida_file selected_file(result, ida_file::open_mode::binary_read_only);
> 
> 		auto image_base = get_real_imagebase();
> 		msg("Imagebase: 0x%llX\n", image_base);
> 
> 		hook_type_t processor_hook = HT_IDP;
> 
> 		if (selected_file.is_open())
> 		{
> 			while (selected_file.can_read_more())
> 			{
> 				uint32 offset = selected_file.read<uint32>();
> 				uint16 name_len = selected_file.read<uint16>();
> 
> 				ida_string name_string = selected_file.read_string(name_len);
> 
> 				set_name(image_base + offset, name_string.c_str(), SN_DELTAIL);
> 
> 				//msg("offset: 0x%X\n", offset);
> 				//msg("name_len: 0x%X\n", name_len);
> 				//msg("name_string: %s\n", name_string.c_str());
> 			}
> 		}
> 
> 		return true;
> 	}
> };
> 
> 
> //--------------------------------------------------------------------------
> static plugmod_t* idaapi init(void)
> {
> 	return new plugin_ctx_t;
> }
> 
> //--------------------------------------------------------------------------
> plugin_t PLUGIN =
> {
>   IDP_INTERFACE_VERSION,
>   PLUGIN_UNL            // Unload the plugin immediately after calling 'run'
>   | PLUGIN_MULTI,       // The plugin can work with multiple idbs in parallel
>   init,                 // initialize
>   nullptr,
>   nullptr,
>   nullptr,              // long comment about the plugin
>   nullptr,              // multiline help about the plugin
>   "IDAExecFunctionsImporter", // the preferred short name of the plugin
>   "Ctrl-Alt-A",         // the preferred hotkey to run the plugin
> };`
> ```

this work fr?

**Comment by AlestackOverglow** [comment]
> > Your ida 9 fork is not work, so take working code:
> > ```
> > `#include <Windows.h>
> > #include <ida.hpp>
> > #include <idp.hpp>
> > #include <loader.hpp>
> > #include <bytes.hpp>
> > #include <funcs.hpp>
> > #include <fpro.h>
> > #include <name.hpp>
> > #include <diskio.hpp>
> > #include <kernwin.hpp>
> > 
> > #include "ida_file.h"
> > #include "ida_string.h"
> > 
> > size_t get_real_imagebase()
> > {
> > 	return getinf(INF_IMAGEBASE);
> > }
> > 
> > class plugin_ctx_t : public plugmod_t
> > {
> > public:
> > 	// Constructor
> > 	plugin_ctx_t()
> > 	{
> > 		msg("MyPlugmod: Constructor called.\n");
> > 	}
> > 
> > 	// Destructor
> > 	virtual ~plugin_ctx_t()
> > 	{
> > 		msg("MyPlugmod: Destructor called.\n");
> > 	}
> > 	virtual bool idaapi run(size_t) override
> > 	{
> > 		ida_string result = ask_file(false, "*.idmap", "Load the file, or %s", "die!");
> > 		
> > 		ida_file selected_file(result, ida_file::open_mode::binary_read_only);
> > 
> > 		auto image_base = get_real_imagebase();
> > 		msg("Imagebase: 0x%llX\n", image_base);
> > 
> > 		hook_type_t processor_hook = HT_IDP;
> > 
> > 		if (selected_file.is_open())
> > 		{
> > 			while (selected_file.can_read_more())
> > 			{
> > 				uint32 offset = selected_file.read<uint32>();
> > 				uint16 name_len = selected_file.read<uint16>();
> > 
> > 				ida_string name_string = selected_file.read_string(name_len);
> > 
> > 				set_name(image_base + offset, name_string.c_str(), SN_DELTAIL);
> > 
> > 				//msg("offset: 0x%X\n", offset);
> > 				//msg("name_len: 0x%X\n", name_len);
> > 				//msg("name_string: %s\n", name_string.c_str());
> > 			}
> > 		}
> > 
> > 		return true;
> > 	}
> > };
> > 
> > 
> > //--------------------------------------------------------------------------
> > static plugmod_t* idaapi init(void)
> > {
> > 	return new plugin_ctx_t;
> > }
> > 
> > //--------------------------------------------------------------------------
> > plugin_t PLUGIN =
> > {
> >   IDP_INTERFACE_VERSION,
> >   PLUGIN_UNL            // Unload the plugin immediately after calling 'run'
> >   | PLUGIN_MULTI,       // The plugin can work with multiple idbs in parallel
> >   init,                 // initialize
> >   nullptr,
> >   nullptr,
> >   nullptr,              // long comment about the plugin
> >   nullptr,              // multiline help about the plugin
> >   "IDAExecFunctionsImporter", // the preferred short name of the plugin
> >   "Ctrl-Alt-A",         // the preferred hotkey to run the plugin
> > };`
> > ```
> 
> this work fr?

Yes, compile with ida 9 pro sdk

**Comment by FlashCoder2024** [comment]
> > > Your ida 9 fork is not work, so take working code:
> > > ```
> > > `#include <Windows.h>
> > > #include <ida.hpp>
> > > #include <idp.hpp>
> > > #include <loader.hpp>
> > > #include <bytes.hpp>
> > > #include <funcs.hpp>
> > > #include <fpro.h>
> > > #include <name.hpp>
> > > #include <diskio.hpp>
> > > #include <kernwin.hpp>
> > > 
> > > #include "ida_file.h"
> > > #include "ida_string.h"
> > > 
> > > size_t get_real_imagebase()
> > > {
> > > 	return getinf(INF_IMAGEBASE);
> > > }
> > > 
> > > class plugin_ctx_t : public plugmod_t
> > > {
> > > public:
> > > 	// Constructor
> > > 	plugin_ctx_t()
> > > 	{
> > > 		msg("MyPlugmod: Constructor called.\n");
> > > 	}
> > > 
> > > 	// Destructor
> > > 	virtual ~plugin_ctx_t()
> > > 	{
> > > 		msg("MyPlugmod: Destructor called.\n");
> > > 	}
> > > 	virtual bool idaapi run(size_t) override
> > > 	{
> > > 		ida_string result = ask_file(false, "*.idmap", "Load the file, or %s", "die!");
> > > 		
> > > 		ida_file selected_file(result, ida_file::open_mode::binary_read_only);
> > > 
> > > 		auto image_base = get_real_imagebase();
> > > 		msg("Imagebase: 0x%llX\n", image_base);
> > > 
> > > 		hook_type_t processor_hook = HT_IDP;
> > > 
> > > 		if (selected_file.is_open())
> > > 		{
> > > 			while (selected_file.can_read_more())
> > > 			{
> > > 				uint32 offset = selected_file.read<uint32>();
> > > 				uint16 name_len = selected_file.read<uint16>();
> > > 
> > > 				ida_string name_string = selected_file.read_string(name_len);
> > > 
> > > 				set_name(image_base + offset, name_string.c_str(), SN_DELTAIL);
> > > 
> > > 				//msg("offset: 0x%X\n", offset);
> > > 				//msg("name_len: 0x%X\n", name_len);
> > > 				//msg("name_string: %s\n", name_string.c_str());
> > > 			}
> > > 		}
> > > 
> > > 		return true;
> > > 	}
> > > };
> > > 
> > > 
> > > //--------------------------------------------------------------------------
> > > static plugmod_t* idaapi init(void)
> > > {
> > > 	return new plugin_ctx_t;
> > > }
> > > 
> > > //--------------------------------------------------------------------------
> > > plugin_t PLUGIN =
> > > {
> > >   IDP_INTERFACE_VERSION,
> > >   PLUGIN_UNL            // Unload the plugin immediately after calling 'run'
> > >   | PLUGIN_MULTI,       // The plugin can work with multiple idbs in parallel
> > >   init,                 // initialize
> > >   nullptr,
> > >   nullptr,
> > >   nullptr,              // long comment about the plugin
> > >   nullptr,              // multiline help about the plugin
> > >   "IDAExecFunctionsImporter", // the preferred short name of the plugin
> > >   "Ctrl-Alt-A",         // the preferred hotkey to run the plugin
> > > };`
> > > ```
> > 
> > 
> > this work fr?
> 
> Yes, compile with ida 9 pro sdk

how i do that?

**Comment by AlestackOverglow** [comment]
Download sdk and follow instruction in orig repo or just take dll from my fork and use that

**Comment by Fischsalat** [comment]
create a pullrequst for this

**Comment by AlestackOverglow** [comment]
> create a pullrequst for this

Got it. Maybe you should move ida7 plugin to new brunch and update master

**Comment by Fischsalat** [comment]
That was my plan. Thank you for your work.

**Comment by FlashCoder2024** [comment]
> Download sdk and follow instruction in orig repo or just take dll from my fork and use that
> 
> 
> 
> 

Where can I download the SDK?

**Comment by Fischsalat** [comment]
You can get it on various online sites or with the installation of the official IDA client (recommended [if you're rich]). You'll find it if you search.

**Comment by AlestackOverglow** [comment]
> > Download sdk and follow instruction in orig repo or just take dll from my fork and use that
> 
> Where can I download the SDK?

your ida installation folder -> idasdk

**Comment by FlashCoder2024** [comment]
> > > Download sdk and follow instruction in orig repo or just take dll from my fork and use that
> 
> > 
> 
> > Where can I download the SDK?
> 
> 
> 
> your ida installation folder -> idasdk
> 
> 
Okay thanks
