### ISSUE TITLE
The plug-in option you developed cannot be found in IDA's plug-ins

### ISSUE THREAD

**Issue by Ryen1999** [Fischsalat/IDAExecFunctionsImporter#5]
![Uploading image.png…]()

**Comment by Ryen1999** [comment]
![Uploading 1.png…]()

**Comment by Ryen1999** [comment]
![image](https://github.com/user-attachments/assets/2db97462-c5ea-422e-9379-025cf425fc66)

**Comment by Fischsalat** [comment]
compile it for the right version and build it in x64
